export const categoryIds = ["adult", "social", "news", "sports", "shopping", "gambling"] as const;

export type CategoryId = (typeof categoryIds)[number];

export const alwaysBlockedCategoryIds = [
  "adult",
  "gambling",
] as const satisfies readonly CategoryId[];

export function isAlwaysBlockedCategory(categoryId: CategoryId) {
  return alwaysBlockedCategoryIds.some((id) => id === categoryId);
}

export type BlockCategory = {
  id: CategoryId;
  label: string;
  description: string;
  domains: readonly string[];
};

export const blockCategories = [
  {
    id: "adult",
    label: "Adult",
    description: "Adult content and explicit entertainment websites.",
    domains: [
      "bongacams.com",
      "brazzers.com",
      "cam4.com",
      "chaturbate.com",
      "erome.com",
      "fansly.com",
      "livejasmin.com",
      "literotica.com",
      "motherless.com",
      "nhentai.net",
      "onlyfans.com",
      "pornhub.com",
      "redtube.com",
      "rule34.xxx",
      "spankbang.com",
      "stripchat.com",
      "xhamster.com",
      "xnxx.com",
      "xvideos.com",
      "youporn.com",
    ],
  },
  {
    id: "social",
    label: "Social",
    description: "Social networks, communities, messaging, and discussion platforms.",
    domains: [
      "bsky.app",
      "discord.com",
      "facebook.com",
      "instagram.com",
      "linkedin.com",
      "mastodon.social",
      "meetup.com",
      "nextdoor.com",
      "pinterest.com",
      "quora.com",
      "reddit.com",
      "snapchat.com",
      "t.me",
      "telegram.org",
      "threads.net",
      "tiktok.com",
      "tumblr.com",
      "vk.com",
      "weibo.com",
      "whatsapp.com",
      "x.com",
    ],
  },
  {
    id: "news",
    label: "News",
    description: "General news, politics, business news, and current events websites.",
    domains: [
      "abcnews.go.com",
      "aljazeera.com",
      "apnews.com",
      "axios.com",
      "bbc.com",
      "bbc.co.uk",
      "bloomberg.com",
      "cbsnews.com",
      "cnn.com",
      "economist.com",
      "foxnews.com",
      "huffpost.com",
      "nbcnews.com",
      "newsweek.com",
      "npr.org",
      "nytimes.com",
      "politico.com",
      "reuters.com",
      "theguardian.com",
      "time.com",
      "washingtonpost.com",
      "wsj.com",
    ],
  },
  {
    id: "sports",
    label: "Sports",
    description: "Sports news, scores, leagues, teams, and live match coverage.",
    domains: [
      "as.com",
      "bleacherreport.com",
      "cbssports.com",
      "cricbuzz.com",
      "espn.com",
      "espncricinfo.com",
      "fifa.com",
      "flashscore.com",
      "formula1.com",
      "goal.com",
      "livescore.com",
      "marca.com",
      "mlb.com",
      "nba.com",
      "nbcsports.com",
      "nfl.com",
      "nhl.com",
      "olympics.com",
      "skysports.com",
      "sofascore.com",
      "sports.yahoo.com",
      "theathletic.com",
      "uefa.com",
    ],
  },
  {
    id: "shopping",
    label: "Shopping",
    description: "Online stores, marketplaces, fashion, electronics, and retail websites.",
    domains: [
      "aliexpress.com",
      "amazon.com",
      "asos.com",
      "bestbuy.com",
      "costco.com",
      "ebay.com",
      "etsy.com",
      "homedepot.com",
      "ikea.com",
      "lowes.com",
      "macys.com",
      "newegg.com",
      "nordstrom.com",
      "shein.com",
      "target.com",
      "temu.com",
      "walmart.com",
      "wayfair.com",
      "wish.com",
      "zalando.com",
    ],
  },
  {
    id: "gambling",
    label: "Gambling",
    description: "Online casinos, sportsbooks, poker, and betting websites.",
    domains: [
      "888casino.com",
      "bet365.com",
      "betfair.com",
      "betmgm.com",
      "betway.com",
      "bovada.lv",
      "caesars.com",
      "coral.co.uk",
      "draftkings.com",
      "fanduel.com",
      "ladbrokes.com",
      "paddypower.com",
      "pokerstars.com",
      "pointsbet.com",
      "roobet.com",
      "sportsbet.com.au",
      "stake.com",
      "tab.com.au",
      "unibet.com",
      "williamhill.com",
    ],
  },
] as const satisfies readonly BlockCategory[];
