export const defaultAdultKeywords = [
  "backshots",
  "bop",
  "latina",
  "baddie",
  "asiantapes",
  "banglaporn",
  "bongacams",
  "brazzers",
  "bukkake",
  "chaturbate",
  "horny",
  "carsex",
  "chodai",
  "chudai",
  "chudayi",
  "coomerparty",
  "throat",
  "creampie",
  "cumshot",
  "ass",
  "cum",
  "thowing it back",
  "throwin it backs",
  "deepthroat",
  "slutty",
  "sloppy",
  "desinudes",
  "desiporn",
  "threesome",
  "facefuck",
  "onfours",
  "on fours",
  "onallfours",
  "desisex",
  "erome",
  "erothots",
  "missionary",
  "fapello",
  "fansly",
  "fikfap",
  "bopper",
  "OF",
  "pawg",
  "POV",
  "wmaf",
  "mzansipeaches",
  "mzansi",
  "cumshot",
  "bwc",
  "bbc",
  "raceplay",
  "anal",
  "slurp",
  "slurplay",
  "ebony",
  "bleached",
  "bwwm",
  "cheatinggf",
  "cheatingwife",
  "cuckold",
  "cuckquean",
  "cuckcake",
  "hotwife",
  "hugecock",
  "homewrecker",
  "kink",
  "hugeboobs",
  "cum",
  "fucktoy",
  "hugetits",
  "hugeass",
  "hugebutt",
  "throatjob",
  "blowjob",
  "freeuse",
  "snowbunny",
  "sellingcontent",
  "twoman",
  "2man",
  "cucked",
  "wmaf",
  "cougar",
  "gangbang",
  "goonette",
  "gooning",
  "hentai",
  "indianporn",
  "livejasmin",
  "literotica",
  "manyvids",
  "milf",
  "motherless",
  "nhentai",
  "nsfw",
  "nsfwtwt",
  "onlyfans",
  "onlyfansleaks",
  "pakistaniporn",
  "porn",
  "pornhub",
  "pornhwa",
  "pornwha",
  "porntwt",
  "redgifs",
  "redtube",
  "rule34",
  "simpcity",
  "spankbang",
  "stepmom",
  "stripchat",
  "thothub",
  "wataa",
  "xhamster",
  "xnxx",
  "amateur",
  "riding",
  "xvideos",
  "youporn",
] as const;

export const defaultAdultKeywordDomains = [
  "x.com",
  "twitter.com",
  "reddit.com",
  "instagram.com",
] as const;

const normalizedDefaultAdultKeywords = new Set(
  defaultAdultKeywords.map((keyword) => keyword.toLowerCase()),
);

export function isDefaultAdultKeyword(keyword: string) {
  return normalizedDefaultAdultKeywords.has(keyword.trim().toLowerCase());
}
